version: '2'

services: 
  beagle_home:
    image: nginx
    restart: always
    container_name: beagle_home
    volumes:
      - ./html:/usr/share/nginx/html
    labels:
      - "traefik.docker.network=thenetwork"
      - "traefik.enable=true"
      - "traefik.port=80"
      - "traefik.backend=beagle_home"
      - "traefik.frontend.rule=Host:beagle.lib.virginia.edu"

networks:
  default:
    external:
      name: thenetwork
